### ISSUE TITLE
TODO - make your code good

### ISSUE THREAD

**Issue by Mr-VIT** [XtraCube/AllOfUsBot#1]
- [x] `AllOfUs.cs` make like https://github.com/Impostor/Impostor/blob/dev/src/Impostor.Plugins.Example/ExamplePlugin.cs + https://github.com/Impostor/Impostor/blob/dev/src/Impostor.Plugins.Example/ExamplePluginStartup.cs
- [x] call function (botSendMessage) instead of repeating code
https://github.com/XtraCube/AllOfUsBot/blob/b0c7646b792df623c0c7d9c2274d1ebb27e7fed0/AllOfUs/GameEventListener.cs#L95-L100
- [x] no need interpolate string vars: `SetNameAsync(botname)` instead of `($"{botname}")`
- [x] no need string interpolation without vars: https://github.com/XtraCube/AllOfUsBot/blob/b0c7646b792df623c0c7d9c2274d1ebb27e7fed0/AllOfUs/GameEventListener.cs#L97

` if (args[1].ToLower() == "red"){}...  if (args[1].ToLower() == "blue")... `
- [x] call `.ToLower()` once and save into var
- [x] add `else` or better use `switch` instead of `if{}if{}...`
- [x] remove empty Event Listeners

**Comment by XtraCube** [comment]
Fixed all the issues. Thank you for recommending these changes
